services:
  gateway:
    image: kvin/gateway@sha256:27fc6872836712c640d22397e4cf86c3e771ebed0116e075dca0eb170d9a9081
    volumes:
      - /var/run/dstack.sock:/var/run/dstack.sock
      - /dstack:/dstack
      - data:/data
    network_mode: host
    privileged: true
    environment:
      - WG_ENDPOINT=${WG_ENDPOINT}
      - SRV_DOMAIN=${SRV_DOMAIN}
      - CF_API_TOKEN=${CF_API_TOKEN}
      - CF_ZONE_ID=${CF_ZONE_ID}
      - MY_URL=${MY_URL}
      - BOOTNODE_URL=${BOOTNODE_URL}
      - ACME_STAGING=${ACME_STAGING}
      - SUBNET_INDEX=${SUBNET_INDEX}
      - RUST_LOG=info,certbot=debug
      - PCCS_URL=${PCCS_URL}
      - RPC_DOMAIN=${RPC_DOMAIN}
    restart: always

volumes:
  data:
